
class MyObject {

    fn hop {
      console.log("Hmm");
    }

    fn push(
        value1 :Int,
        value2,
        value3 :Int,
        value4 :Int,
        value5,
        value6,
    ) {

    }

    fn pop :Int {

    }

    var test = 42;
    let tutu = 77;
    
    var arr = [
        42,
    ]
    var bob = {
        toto: 444,
    }

}

let bob :Int = 222;

var hop :(Int, Double) = (42, "Test");
