
class MySubNumber :Number<Int> {

    fn _op_ :String {

    }

}

class MyObject {

    fn @init {

    }
    fn @delete {

    }

    fn $_add:String (a:String) {
        return a;
    }
    fn $_access (key: String) {

    }

    fn $_op_add (a :MyObject, b :MyObject) {

    }

    static fn hop {
      console.log("Hmm");
    }

    fn push(
        value1 :Int,
        value2,
        value3 :Int,
        value4 :Int,
        value5,
        value6,
    ) {

    }

    static fn pop :Int {

    }

    var test = 42;
    let tutu = 77;
    
    var arr = [
        42,
    ]
    var bob = {
        toto: 444,
    }

}

let bob :Int = 222;

var hop :(Int, Double) = (42, "Test");
