//import Tjs

fn rand(valid :Bool)
{
    return async
    {
        Tjs.Wait(fn ()
        {
            if (valid)
            {
                resolve 42;
            }
            else
            {
                reject "Woops";
            }
        });
    }
}

var success: @Number = rand(true);
var failing: @Number = rand(false);

var v1 = 1;
var v2 = 2;
var v3 = 3;
var v4 = 4;
var v5 = @success;

try
{
    v1 = 88;
    v2 = @failing;
    v3 = 89;
}
catch (e :String)
{
    v4 = 90;
}

assert.equal(v1, 88);
assert.equal(v2, 2);
assert.equal(v3, 3);
assert.equal(v4, 90);
assert.equal(v5, 42);
