
// Hello
let test = 42;
var test2 = 42;

fn {
    return 42;
};

function untyped_noparam_fn () {
    
    function nestedFunction () {

    }

}

function untyped_oneparam_fn (param,) {

}

function untyped_oneparam_fn2 (param) {
    
}

function untyped_twoparam_fn3 (param, param2) {
    
}

function typed_oneparam_fn :Int (param1 :Int) {

}

function typed_twoparam_fn :Int (param1 :Int, param2 :String,) {
    42;
    //return 42 + 22 / 23;
    return 44;
}

fn untyped_noparam_fn2 {
    
    fn nestedFunction2 {

        console.log("ABC", "BCD");
        console.log("ABC", "BCD");

        console.log("test", @ttt);

        console.log("ABC", "BCD");

        console.log("ABC", "BCD");
        console.log("ABC", "BCD");

        console.log("ABC", "BCD");
        console.log("ABC", "BCD");

        console.log("ABC", "BCD");
        console.log("ABC", "BCD");

        console.log("ABC", "BCD");
        console.log("ABC", "BCD");
        console.log("ABC", "BCD");
        console.log("ABC", "BCD");
    }

}
