
class Simple : Object
{

}

class Test1 : Object
{

    public var tutu :Int = 42;

    /*
    op new ()
    {
        this.tutu = 41;
    }

    op new (a :int)
    {
        this.tutu = a;
    }

    op + :Int (a :test1, :Int)
    {
    }

    op [] :Int (idx :Int)
    {
        return tutu;
    }

    op del ()
    {
        
    }
    */

}


var test2 = class :Test1
{

    /*
    op new (a :int)
    {
        base.<new>(a);
    }

    op [] :Int (idx :Int)
    {
        let base = (Base)this;
        let this = (This)this;
        return base.<[]>(idx) + 1;
        return base[idx] + 1;
    }
    */

};

var obj1 = new Test1();
var obj2 = new test2(10); // Should throw is not a class if failed

Debug.log(obj1[42]);
Debug.log(obj2[42]);
