
fn testDeasync (hop) {

  var prep :Int;

  while 1 {
    if 42 {
      if false {
          return (prep + 42) + 88;
      } else {
          return -1;
      }
    } else {
      return -2;
    }
  }

}

fn testDeasync2 (hop) {

  var prep :@Int;

  while 1 {
    if 42 {
      if false {
        return (@prep + 42) + 88;
      } else {
        return -1;
      }
    } else {
      return -2;
    }
  }

}
