
import Web.Http;
import Console;

var urls = [
    "https://www.google.com",
    "https://www.cnn.com",
    "https://www.wikipedia.com",
];

// Create an array of async values (one for each URL)
var responses :[@Web.Http.Response] = [];
for url in urls {
    responses.push(Web.Http.get(url));
}

// Wait for all async value to be resolved and loop over results
for result in @all(responses, 5000) // Optional timeout of 5000ms
{
    Console.log(
        "Download done",
        result.url,
        result.code,
        result.text.length,
    );
}
